server:
  port: 18888

mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://${docker.mysql.ip}/nl2sql_standard_database
    username: ${docker.mysql.user}
    password: ${docker.mysql.password}
    driverClassName: com.mysql.cj.jdbc.Driver

  elasticsearch:
    rest:
      uris: http://${docker.mysql.ip}:9200
    socket-timeout: "10s"
    username: ${docker.elasticsearch.user}
    password: ${docker.elasticsearch.password}
