server:
  port: 18888

mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://${mysql.ip}/nl2sql_standard_database
    username: ${mysql.user}
    password: ${mysql.password}
    driverClassName: com.mysql.cj.jdbc.Driver
