server:
  port: 18888

logging:
  level:
    org.springframework.boot.context.config: DEBUG

mybatis:
  mapper-locations: classpath:mapper/*.xml

milvus:
  token: ${docker_milvus_token}
  url: ${docker_milvus_url}
  collections:
    standard_column:
      name: "standard_column_milvus"
      dense_vector_field: "column_comment_dense_vector"
      sparse_vector_field: "column_comment_sparse_vector"
    standard_table:
      name: "standard_table_milvus"
      dense_vector_field: "table_comment_dense_vector"
      sparse_vector_field: "table_comment_sparse_vector"

spring:
  datasource:
    url: jdbc:mysql://${docker_mysql_ip}/nl2sql_standard_database
    username: ${docker_mysql_user}
    password: ${docker_mysql_password}
    driverClassName: com.mysql.cj.jdbc.Driver

ollama:
  embedding:
    model: "bge-m3"
    url: ${docker_ollama_embedding_url}


